os: linux
  dist: trusty

language: python

python:
   - "3.5"

before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends \
   texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra \
   texlive-latex-recommended dvipng"

- sudo apt-get update -y; sudo apt-get -y install tk8.6 tcl8.6 tcl8.6-dev tk8.6-dev
- git clone https://github.com/fangohr/oommf.git && cd oommf && make
- export OOMMF_TK_CONFIG=/usr/lib/x86_64-linux-gnu/tk8.6/tkConfig.sh
- export OOMMF_TCL_CONFIG=/usr/lib/x86_64-linux-gnu/tcl8.6/tclConfig.sh
- alias oommf="tclsh ${OOMMF_TCL}/oommf.tcl"

script:
  py.test --version
