os: linux
dist: trusty

env:
  OOMMFTCL=/opt/oommf/oommf/oommf.tcl

language: python

python:
   - "3.5"

before_install:
- "sudo apt-get update && sudo apt-get install --no-install-recommends \
   texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra \
   texlive-latex-recommended dvipng"

- export OOMMF_TK_CONFIG=/usr/lib/x86_64-linux-gnu/tk8.6/tkConfig.sh
- export OOMMF_TCL_CONFIG=/usr/lib/x86_64-linux-gnu/tcl8.6/tclConfig.sh
- sudo apt-get update -y
- sudo apt-get -y install tk8.6 tcl8.6 tcl8.6-dev tk8.6-dev
- pwd
- mkdir -p /opt
- cd /opt && git clone https://github.com/fangohr/oommf.git && cd oommf && make



script:
  - pwd
  - cd
  - pwd
  - py.test --version
  - echo $PATH
  - python --version
  - echo $OOMMFTCL
  - tclsh ${OOMMFTCL} +version
  - make unit-tests
  - make reproduce-figures-from-oommf-reference-data
  - make recompute-oommf-data
  - make compare-data
  - make reproduce-figures-from-oommf-recomputed-data
